apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-nginx
spec:
  replicas: 3
  serviceName: sts-service
#  podManagementPolicy: OrderedReady  # default value
#  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webui
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14
