- name: Service Check 
  hosts: kube
  gather_facts: no
  tasks:
  - name: Stop/disable the services
    service:
      name: "{{ item }}"  
      state: stopped
      enabled: no
    loop:
    - httpd
    - named
    - vsftpd
    - sendmail
    - dovecot
  - name: Start/enable the services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    loop:
    - chronyd
